console.log('hello nodejs');
console.log(1000 + 999);
console.log(setTimeout);
console.log(setInterval);
// console.log(requestAnimationFrame);
console.log(setImmediate);
console.log(process);
console.log(process.argv);
console.log(process.argv0);
console.log(process.arch);
console.log(process.platform);
console.log(process.kill);
console.log(process.exit);
console.log(process.cpuUsage());
console.log(process.memoryUsage.rss());
console.log(process.cwd());
console.log(process.pid);
console.log(process.version);
console.log(process.versions);